# Generated by Django 5.0.7 on 2024-08-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='column_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CSVData',
        ),
    ]
