# Generated by Django 5.0.7 on 2024-08-09 10:07

import b_mmm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0003_alter_csvfile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='upload_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to=b_mmm.models.get_file_path),
        ),
    ]
