# Generated by Django 5.0.7 on 2024-08-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0004_rename_upload_date_csvfile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='column_names',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='date_column',
            field=models.CharField(default='date', max_length=255),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='predictor_columns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='sales_column',
            field=models.CharField(default='sales', max_length=255),
        ),
    ]
