# Generated by Django 5.0.7 on 2024-08-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0005_remove_csvfile_column_names_csvfile_date_column_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'CSV File', 'verbose_name_plural': 'CSV Files'},
        ),
        migrations.AddField(
            model_name='csvfile',
            name='currency',
            field=models.CharField(default='€', max_length=3),
        ),
    ]
