# Generated by Django 5.0.7 on 2024-08-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0006_alter_csvfile_options_csvfile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='predictor_currencies',
            field=models.JSONField(default=list),
        ),
    ]
