# Generated by Django 5.0.7 on 2024-08-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0010_alter_marketingmixmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmixmodel',
            name='trace_plot',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
    ]
