# Generated by Django 5.0.7 on 2024-08-14 11:52

import b_mmm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0011_marketingmixmodel_trace_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmixmodel',
            name='trace_plot',
            field=models.ImageField(blank=True, null=True, upload_to=b_mmm.models.get_plot_path),
        ),
    ]
