# Generated by Django 5.0.7 on 2024-08-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0014_marketingmixmodel_y_posterior_predictive_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingmixmodel',
            name='model_type',
        ),
    ]
