# Generated by Django 5.0.7 on 2024-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0015_remove_marketingmixmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmixmodel',
            name='trace_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingmixmodel',
            name='y_posterior_predictive_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
