# Generated by Django 5.0.7 on 2024-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0016_marketingmixmodel_trace_binary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmixmodel',
            name='mmm_model_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
