# Generated by Django 5.0.7 on 2024-08-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0017_marketingmixmodel_mmm_model_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingmixmodel',
            name='mmm_model_binary',
        ),
    ]
