# Generated by Django 5.0.7 on 2024-08-16 15:24

import b_mmm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0018_remove_marketingmixmodel_mmm_model_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmixmodel',
            name='error_percent_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingmixmodel',
            name='error_percent_plot',
            field=models.ImageField(blank=True, null=True, upload_to=b_mmm.models.get_plot_path),
        ),
        migrations.AddField(
            model_name='marketingmixmodel',
            name='n_posterior_samples',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
