# Generated by Django 5.0.7 on 2024-08-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0019_marketingmixmodel_error_percent_binary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmixmodel',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='marketingmixmodel',
            name='results',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
