# Generated by Django 5.0.7 on 2024-09-25 17:46

import b_mmm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0021_marketingmixmodel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingmixmodel',
            name='error_percent_binary',
        ),
        migrations.RemoveField(
            model_name='marketingmixmodel',
            name='n_posterior_samples',
        ),
        migrations.RemoveField(
            model_name='marketingmixmodel',
            name='parameter_posteriors_plot',
        ),
        migrations.RemoveField(
            model_name='marketingmixmodel',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='marketingmixmodel',
            name='results',
        ),
        migrations.RemoveField(
            model_name='marketingmixmodel',
            name='trace_binary',
        ),
        migrations.RemoveField(
            model_name='marketingmixmodel',
            name='y_posterior_predictive_binary',
        ),
        migrations.AddField(
            model_name='marketingmixmodel',
            name='saved_mmm',
            field=models.FileField(blank=True, null=True, upload_to=b_mmm.models.get_model_path),
        ),
    ]
