# Generated by Django 5.0.7 on 2024-09-26 12:33

import b_mmm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0022_remove_marketingmixmodel_error_percent_binary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='cleaned_data_file',
            field=models.FileField(blank=True, null=True, upload_to=b_mmm.models.get_cleaned_file_path),
        ),
    ]
