# Generated by Django 5.0.7 on 2024-09-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_mmm', '0023_csvfile_cleaned_data_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='date_column',
            new_name='date_name',
        ),
        migrations.RenameField(
            model_name='csvfile',
            old_name='predictor_columns',
            new_name='predictor_names',
        ),
        migrations.RenameField(
            model_name='csvfile',
            old_name='sales_column',
            new_name='sales_name',
        ),
    ]
